version: '2'
services:

  fluentd:
    image: vevo/fluentd-elasticsearch
    links:
      - "elasticsearch"
    ports:
      - "24224:24220"
      - "24224:24220/udp"
    logging:
        driver: "json-file"
        options:
            max-size: 100m
            max-file: "5"

  elasticsearch:
    image: elasticsearch:7.7.0
    environment:
      - discovery.type=single-node
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.7.0
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"

